import { addDays, toDateKey } from "./date-utils";
import { WorkspaceData } from "./types";

export function createInitialWorkspace(): WorkspaceData {
  const now = new Date();
  const today = toDateKey(now);
  const tomorrow = toDateKey(addDays(now, 1));
  const laterThisWeek = toDateKey(addDays(now, 3));
  const nextWeek = toDateKey(addDays(now, 7));
  const createdAt = now.toISOString();

  return {
    version: 1,
    tasks: [
      {
        id: "task-launch",
        title: "Finalize Q3 launch plan",
        description: "Align the milestones, owners, and risk plan before the team review.",
        priority: "high",
        dueDate: today,
        status: "in-progress",
        project: "Product",
        createdAt,
        updatedAt: createdAt,
      },
      {
        id: "task-research",
        title: "Send research synthesis",
        description: "Turn the interview takeaways into a concise decision memo.",
        priority: "medium",
        dueDate: tomorrow,
        status: "todo",
        project: "Research",
        createdAt,
        updatedAt: createdAt,
      },
      {
        id: "task-interviews",
        title: "Book customer interviews",
        description: "Confirm the next five customer conversations.",
        priority: "low",
        dueDate: laterThisWeek,
        status: "todo",
        project: "Growth",
        createdAt,
        updatedAt: createdAt,
      },
      {
        id: "task-onboarding",
        title: "Update onboarding checklist",
        description: "Capture the workflow improvements from the latest cohort.",
        priority: "medium",
        dueDate: nextWeek,
        status: "done",
        project: "Operations",
        createdAt,
        updatedAt: createdAt,
      },
    ],
    notes: [
      {
        id: "note-launch",
        title: "Launch notes",
        body: "A few thoughts after the customer call. The clearest value is the calm, focused workspace—not more process.",
        category: "Product",
        color: "#F4B3A3",
        createdAt,
        updatedAt: createdAt,
        pinned: true,
      },
      {
        id: "note-ideas",
        title: "Ideas to explore",
        body: "What if the first-run experience felt more like a personal briefing than an empty dashboard?",
        category: "Ideas",
        color: "#F4D98B",
        createdAt,
        updatedAt: createdAt,
        pinned: false,
      },
      {
        id: "note-rituals",
        title: "Team rituals",
        body: "Keep the Monday kickoff short and useful. Make room for one clear priority and one kind check-in.",
        category: "Team",
        color: "#C4E3D5",
        createdAt,
        updatedAt: createdAt,
        pinned: false,
      },
    ],
    events: [
      {
        id: "event-focus",
        title: "Deep work block",
        date: today,
        time: "09:00",
        duration: "2h",
        description: "Protect time for the launch plan and synthesis work.",
        attendees: [],
        color: "#F4B3A3",
      },
      {
        id: "event-design",
        title: "Design review with Maya",
        date: today,
        time: "14:00",
        duration: "45m",
        description: "Review the workspace flows and resolve open interaction questions.",
        attendees: ["Maya Singh"],
        color: "#BED8EA",
      },
      {
        id: "event-wrap",
        title: "Weekly wrap-up",
        date: laterThisWeek,
        time: "16:30",
        duration: "30m",
        description: "Reflect on progress and make a light plan for next week.",
        attendees: [],
        color: "#C4E3D5",
      },
    ],
    team: [
      {
        id: "member-maya",
        initials: "MS",
        name: "Maya Singh",
        role: "Product designer",
        status: "online",
        color: "#F4B3A3",
        project: "Workspace refresh",
        lastActive: "Active now",
      },
      {
        id: "member-jordan",
        initials: "JL",
        name: "Jordan Lee",
        role: "Engineering lead",
        status: "focus",
        color: "#BED8EA",
        project: "Launch platform",
        lastActive: "In focus mode",
      },
      {
        id: "member-kira",
        initials: "KN",
        name: "Kira Nolan",
        role: "Research partner",
        status: "online",
        color: "#C4E3D5",
        project: "Customer insights",
        lastActive: "Active 8m ago",
      },
      {
        id: "member-owen",
        initials: "OB",
        name: "Owen Brooks",
        role: "Growth strategist",
        status: "away",
        color: "#F4D98B",
        project: "Activation experiments",
        lastActive: "Away · 23m ago",
      },
    ],
    settings: {
      profileName: "Alex Rivera",
      email: "alex@studio.co",
      appearance: "system",
      notifications: true,
      language: "English",
      dailyDigest: true,
    },
    activities: [
      {
        id: "activity-maya",
        actor: "Maya Singh",
        message: "shared a new design review agenda",
        timestamp: "12m ago",
        tone: "coral",
      },
      {
        id: "activity-jordan",
        actor: "Jordan Lee",
        message: "moved Launch platform into focus mode",
        timestamp: "34m ago",
        tone: "blue",
      },
      {
        id: "activity-kira",
        actor: "Kira Nolan",
        message: "added two customer interview insights",
        timestamp: "1h ago",
        tone: "mint",
      },
    ],
    focusMinutes: 270,
  };
}
